apiVersion: v1
kind: Service
metadata:
  name: {{ include "tars.backend.serviceName" . }}
  namespace: {{ include "tars.namespace" . }}
  labels:
    {{- include "tars.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    {{- if .Values.prometheus.scrape.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.config.api.port }}"
    prometheus.io/path: "{{ .Values.prometheus.scrape.path }}"
    {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "tars.backend.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.config.api.port }}
    protocol: TCP
  - name: metrics
    port: {{ .Values.backend.service.metricsPort }}
    targetPort: {{ .Values.config.prometheus.port }}
    protocol: TCP
  {{- if eq .Values.backend.service.sessionAffinity "ClientIP" }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.backend.service.sessionAffinityTimeout }}
  {{- end }}
