{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tars.postgresql.serviceName" . }}
  namespace: {{ include "tars.namespace" . }}
  labels:
    {{- include "tars.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.postgresql.service.type }}
  selector:
    {{- include "tars.postgresql.selectorLabels" . | nindent 4 }}
  ports:
  - name: postgres
    port: {{ .Values.postgresql.service.port }}
    targetPort: {{ .Values.postgresql.service.port }}
    protocol: TCP
{{- end }}
