{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tars.redis.serviceName" . }}-service
  namespace: {{ include "tars.namespace" . }}
  labels:
    {{- include "tars.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    {{- include "tars.redis.selectorLabels" . | nindent 4 }}
  ports:
  - name: redis
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.port }}
    protocol: TCP
{{- end }}
